### ISSUE TITLE
Keep songs in correct order when downloading albums

### ISSUE THREAD

**Issue by ghost** [BrightDV/BlackHole#5]
**Is your feature request related to a problem? Please describe.**
When downloading a full album, it will be nice to have the songs in correct order. We can do this by numbering the file names. For eg. the first song of the album will be "01 - <song name>.mp3" etc.

**Describe the solution you'd like**
An option in settings to number the file names when downloading full album.
Maybe we can only have this option when we're downloading the album in a separate folder.

**Additional context**
I'm currently working on this. Will create a PR when done.

**Comment by BrightDV** [comment]
Thanks for the idea, I do agree. However, your solution might not be the best one.
I saw that the app use [metadata_god](https://pub.dev/packages/metadata_god) where we can add the track number (of the album) at the download.

![Image](https://github.com/user-attachments/assets/92483a91-b4d3-4591-9b99-7f5380467327)

Then, the sort could use this metadata, instead of the name of the file (not sure about this one).
In this way, the downloaded files would better integrate in other music players.

**Comment by BrightDV** [comment]
What you have done in your fork seems good, maybe you can open a PR.
However, as there is a huge lack of information from JioSaavn, I will sadly not work on this, as it is pretty much complicated.
